### ISSUE TITLE
Problem with displaying dropdown list.

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vsf-capybara#328]
## Current behavior
Dropdown list does not display correctly.
![image](https://user-images.githubusercontent.com/36628922/79967932-c3e55d80-848f-11ea-84ee-9bad168e83f7.png)
![image](https://user-images.githubusercontent.com/36628922/79968010-dd86a500-848f-11ea-8d66-dab200d1c187.png)
![image](https://user-images.githubusercontent.com/36628922/79967833-a3b59e80-848f-11ea-9ffd-5e25b55ca603.png)

## Expected behavior
Drop-down lists should not be covered by other elements, and should be displayed without shifts.

## Steps to reproduce the issue
1. Go to category page
2. Refresh page
3. See arrow next to `Sort by` drop-down list
4. Expand drop-down list and hover over the second product in PLP
5. Go to PDP and see Size drop-down list

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by psmyrek** [comment]
This problem does not occur on development build, but only in production build. It is related to some issues with CSS specificity and cascade rules.
It is not possible to provide clean fix here in Capybara theme.
It will be probably addressed and fixed in Storefront UI: https://github.com/DivanteLtd/storefront-ui/issues/1087
