### ISSUE TITLE
Update filters bar on category page

### ISSUE THREAD

**Issue by gibkigonzo** [DivanteLtd/vsf-capybara#381]
## Current behavior

In mobile there should be different order for filters bar.
![Image from iOS (1)](https://user-images.githubusercontent.com/42383376/83998189-59fe1600-a960-11ea-8f9e-3fd4f41b327b.png)

## Expected behavior

![Zrzut ekranu z 2020-06-08 08-15-16](https://user-images.githubusercontent.com/42383376/83998196-608c8d80-a960-11ea-9848-f6f61d4b1b33.png)

should be same as is on https://www.figma.com/file/hrwE3VsMBHgdJoS86rVr4W/Desktop-%26-Mobile-Vue-Storefront?node-id=99%3A0

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by AishwaryShrivastav** [comment]
`        <div class="navbar__sort">
          <span class="navbar__label">{{ $t("Sort By") }}:</span>
          <SfSelect
            class="navbar__select sort-by"
            :selected="sortOrder"
            @change="changeSortOder"
          >
            <SfSelectOption
              v-for="option in sortOptions"
              :key="option.id"
              :value="option.id"
              class="sort-by__option"
            >
              {{ option.label }}
            </SfSelectOption>
          </SfSelect>
        </div>
        <div class="navbar__counter">
          <span class="navbar__label desktop-only">
            {{ $t("Products found") }}:
          </span>
          <strong class="desktop-only">{{ getCategoryProductsTotal }}</strong>
          <span class="navbar__label mobile-only">
            {{ $t("{count} items", { count: getCategoryProductsTotal }) }}
          </span>
        </div>`

**Comment by AishwaryShrivastav** [comment]
Hi @gibkigonzo and @pkarw, 
It's happening because on desktop view these in different orders and we have handled the mobile view and desktop view using mobile-only and desktop-only classes in the same section.
We can separate the mobile sections from the desktop section and place them in the orders defined in figma files.
If this solution looks good to you both, I can create a PR for the same, else we can discuss any other way to achive the view as per the figma files. 
![Category vue](https://user-images.githubusercontent.com/8766155/87628462-a4886480-c74e-11ea-9ee6-4fb5153073d8.png)
