### ISSUE TITLE
I want to see tabs with product description, reviews and additional informations on PDP

### ISSUE THREAD

**Issue by qiqqq** [DivanteLtd/vsf-capybara#50]

**Comment by gibkigonzo** [comment]
It's done here https://github.com/DivanteLtd/vsf-capybara/pull/63 and here https://github.com/DivanteLtd/vsf-capybara/pull/65 We need to update add review modal, issue: https://github.com/DivanteLtd/vsf-capybara/issues/87

![Zrzut ekranu z 2020-01-23 08-37-44](https://user-images.githubusercontent.com/42383376/73631167-8d4e3280-4658-11ea-81d8-748517f59658.png)

I didn't add additional info because there isn't something like this in vsf
